import json

internal_links_to_validate = [
    "docapis_what_is_a_rest_api.html", "likeadeveloper.html", "docendpoints.html",
    "docapis_resource_descriptions.html", "docapis_resource_endpoints.html",
    "docapis_doc_parameters.html", "docapis_doc_sample_requests.html",
    "docapis_doc_sample_responses_and_schema.html", "docconceptual.html",
    "docapis_doc_getting_started_section.html", "docapis_doc_overview.html",
    "docapis_doc_status_codes.html", "docapis_more_about_authorization.html",
    "publishingapis.html", "pubapis_github_wikis.html", "pubapis_jekyll.html",
    "pubapis_docs_as_code.html", "pubapis_version_control.html",
    "pubapis_openapi_tutorial_overview.html", "pubapis_openapi_intro.html",
    "nativelibraryapis.html", "nativelibraryapis_create_javadoc.html",
    "docapis_managing_doc_processes.html", "docapis_managing_doc_projects.html",
    "docapis_managing_small_doc_requests.html",
    "docapis_collecting_feedback_post_release.html", "docapis_status_reports.html",
    "docapis_measuring_impact.html", "docapis_quality_checklist.html",
    "docapis_scenario_for_using_weather_api.html", "workshop.html",
    "docapis_find_open_source_project.html", "jobapis.html",
    "docapis_course_videos.html"
]

known_subdirectories = [
    "additional_resources", "code_tutorials", "conceptual_topics_in_api_docs",
    "course_overview", "documenting_api_endpoints", "glossary",
    "introduction_to_rest_apis", "metrics_and_measurement", "native_library_apis",
    "openapi_spec_and_generated_ref_docs", "processes_and_methodology",
    "publishing_api_documentation", "publishing_tools", "step_by_step_openapi_tutorial",
    "testing_api_docs", "the_writing_process", "thriving_in_the_api_doc_space",
    "using_an_api_like_a_developer"
]

# This list is derived from the output of ls("_docs")
repo_files_structure = [
    "_docs/additional_resources/api_doc_presentations.md",
    "_docs/additional_resources/denver_workshop_recordings.md",
    "_docs/additional_resources/docapis_aerisweather_example.md",
    "_docs/additional_resources/docapis_apidoc_survey.html",
    "_docs/additional_resources/docapis_eventbrite_example.md",
    "_docs/additional_resources/docapis_flickr_example.md",
    "_docs/additional_resources/docapis_graphql.md",
    "_docs/additional_resources/docapis_more_rest_exercises.md",
    "_docs/additional_resources/jeopardy_answer_key.md",
    "_docs/additional_resources/menlo_park_workshop_recordings.md",
    "_docs/additional_resources/pubapis_api_blueprint.md",
    "_docs/additional_resources/pubapis_raml.md",
    "_docs/additional_resources/resources.md",
    "_docs/additional_resources/whats_wrong_answer_key.md",
    "_docs/code_tutorials/devx-usability-examples.md",
    "_docs/code_tutorials/docapis_code_difficulty.md",
    "_docs/code_tutorials/docapis_code_sample_apps.md",
    "_docs/code_tutorials/docapis_code_strategies.md",
    "_docs/code_tutorials/docapis_code_tutorials_common_characteristics.md",
    "_docs/code_tutorials/docapis_codesamples_bestpractices.md",
    "_docs/code_tutorials/docapis_research_on_documenting_code.md",
    "_docs/code_tutorials/docapis_sdks.md",
    "_docs/code_tutorials/docapiscode.md",
    "_docs/code_tutorials/evaluating-api-design.md",
    "_docs/conceptual_topics_in_api_docs/docapis_best_practices_with_api.md",
    "_docs/conceptual_topics_in_api_docs/docapis_concept_activity.md",
    "_docs/conceptual_topics_in_api_docs/docapis_conceptual_topics_overview.md",
    "_docs/conceptual_topics_in_api_docs/docapis_doc_getting_started_section.md",
    "_docs/conceptual_topics_in_api_docs/docapis_doc_overview.md",
    "_docs/conceptual_topics_in_api_docs/docapis_doc_quick_reference_guide.md",
    "_docs/conceptual_topics_in_api_docs/docapis_doc_status_codes.md",
    "_docs/conceptual_topics_in_api_docs/docapis_getting_started_activity.md",
    "_docs/conceptual_topics_in_api_docs/docapis_glossary_section.md",
    "_docs/conceptual_topics_in_api_docs/docapis_more_about_authorization.md",
    "_docs/conceptual_topics_in_api_docs/docapis_rate_limiting_and_thresholds.md",
    "_docs/conceptual_topics_in_api_docs/docconceptual.md",
    "_docs/course_overview/docapis_about_the_author.md",
    "_docs/course_overview/docapis_course_reviews.md",
    "_docs/course_overview/docapis_foreword.md",
    "_docs/course_overview/docapis_overview.md",
    "_docs/course_overview/docapis_whats_new.md",
    "_docs/course_overview/download.md",
    "_docs/course_overview/index.md",
    "_docs/course_overview/workshop.md",
    "_docs/documenting_api_endpoints/docapis_api_reference_activity.md",
    "_docs/documenting_api_endpoints/docapis_api_reference_tutorial_overview.md",
    "_docs/documenting_api_endpoints/docapis_api_whats_wrong_activity.md",
    "_docs/documenting_api_endpoints/docapis_doc_parameters.md",
    "_docs/documenting_api_endpoints/docapis_doc_sample_requests.md",
    "_docs/documenting_api_endpoints/docapis_doc_sample_responses_and_schema.md",
    "_docs/documenting_api_endpoints/docapis_finished_doc_result.md",
    "_docs/documenting_api_endpoints/docapis_new_endpoint_to_doc.md",
    "_docs/documenting_api_endpoints/docapis_resource_descriptions.md",
    "_docs/documenting_api_endpoints/docapis_resource_endpoints.md",
    "_docs/documenting_api_endpoints/docendpoints.md",
    "_docs/documenting_api_endpoints/surfreport_endpoint.html",
    "_docs/documenting_api_endpoints/surfreport_parameters.html",
    "_docs/documenting_api_endpoints/surfreport_request.html",
    "_docs/documenting_api_endpoints/surfreport_resource_description.html",
    "_docs/documenting_api_endpoints/surfreport_response.html",
    "_docs/glossary/glossary.md",
    "_docs/glossary/glossary_groups.md",
    "_docs/glossary/glossary_overview.md",
    "_docs/introduction_to_rest_apis/docapis_course_videos.md",
    "_docs/introduction_to_rest_apis/docapis_identify_your_goals.md",
    "_docs/introduction_to_rest_apis/docapis_intro_to_rest_api_doc.md",
    "_docs/introduction_to_rest_apis/docapis_introtoapis.md",
    "_docs/introduction_to_rest_apis/docapis_trends.md",
    "_docs/introduction_to_rest_apis/docapis_what_is_a_rest_api.md",
    "_docs/introduction_to_rest_apis/tocstart_fulldetails.md",
    "_docs/metrics_and_measurement/docapis_metrics_and_measurement.md",
    "_docs/metrics_and_measurement/docapis_metrics_assessing_information_quality.md",
    "_docs/metrics_and_measurement/docapis_metrics_measuring_impact.md",
    "_docs/metrics_and_measurement/docapis_metrics_templates.md",
    "_docs/metrics_and_measurement/docapis_quality_checklist.md",
    "_docs/metrics_and_measurement/docapis_quality_checklist_csv.csv",
    "_docs/metrics_and_measurement/docapis_quality_checklist_html.html",
    "_docs/metrics_and_measurement/docapis_quality_checklist_html_short.html",
    "_docs/metrics_and_measurement/docapis_quantifying_progress.md",
    "_docs/native_library_apis/nativelibraryapis.md",
    "_docs/native_library_apis/nativelibraryapis_create_javadoc.md",
    "_docs/native_library_apis/nativelibraryapis_doxygen.md",
    "_docs/native_library_apis/nativelibraryapis_editing_javadoc.md",
    "_docs/native_library_apis/nativelibraryapis_exploring_javadoc_output.md",
    "_docs/native_library_apis/nativelibraryapis_getting_the_source.md",
    "_docs/native_library_apis/nativelibraryapis_java_crash_course.md",
    "_docs/native_library_apis/nativelibraryapis_javadoc_tags.md",
    "_docs/native_library_apis/nativelibraryapis_nonrefdocs.md",
    "_docs/native_library_apis/nativelibraryapis_overview.md",
    "_docs/openapi_spec_and_generated_ref_docs/openapi_openweathermap.yml",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_combine_swagger_and_guide.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_document360.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_openapi_intro.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_openapis_quickstart_stoplight.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_redoc.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_redocly.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_rest_specification_formats.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_stoplight.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_swagger.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_swagger_demo.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_swagger_ui_standalone.md",
    "_docs/openapi_spec_and_generated_ref_docs/pubapis_swaggerhub_smartbear.md",
    "_docs/openapi_spec_and_generated_ref_docs/restapispecifications.md",
    "_docs/processes_and_methodology/docapis_changing_internal_doc_culture.md",
    "_docs/processes_and_methodology/docapis_collecting_feedback_post_release.md",
    "_docs/processes_and_methodology/docapis_dx_content_strategy.md",
    "_docs/processes_and_methodology/docapis_kickoff_meeting.md",
    "_docs/processes_and_methodology/docapis_managing_doc_processes.md",
    "_docs/processes_and_methodology/docapis_managing_doc_projects.md",
    "_docs/processes_and_methodology/docapis_managing_sdk_releases.md",
    "_docs/processes_and_methodology/docapis_meeting_notes.md",
    "_docs/processes_and_methodology/docapis_processes_for_external_contributors.md",
    "_docs/processes_and_methodology/docapis_release_process.md",
    "_docs/processes_and_methodology/docapis_review_processes.md",
    "_docs/processes_and_methodology/docapis_status_reports.md",
    "_docs/processes_and_methodology/docsapis_doc_maintenance.md",
    "_docs/processes_and_methodology/docsapis_managing_small_doc_requests.md",
    "_docs/processes_and_methodology/pubapis_agile_scrum_for_docs.md",
    "_docs/publishing_api_documentation/pubapis_api_list.md",
    "_docs/publishing_api_documentation/pubapis_design_patterns.md",
    "_docs/publishing_api_documentation/pubapis_docs_as_code.md",
    "_docs/publishing_api_documentation/pubapis_hosting_and_deployment.md",
    "_docs/publishing_api_documentation/pubapis_hybrid_systems.md",
    "_docs/publishing_api_documentation/pubapis_markdown.md",
    "_docs/publishing_api_documentation/pubapis_overview.md",
    "_docs/publishing_api_documentation/pubapis_static_site_generators.md",
    "_docs/publishing_api_documentation/pubapis_version_control.md",
    "_docs/publishing_api_documentation/pubapis_which_tool_to_choose.md",
    "_docs/publishing_api_documentation/publishingapis.md",
    "_docs/publishing_tools/docapis_faq_tools.md",
    "_docs/publishing_tools/pubapis_blobr.md",
    "_docs/publishing_tools/pubapis_github_desktop_client.md",
    "_docs/publishing_tools/pubapis_github_pull_requests.md",
    "_docs/publishing_tools/pubapis_github_wikis.md",
    "_docs/publishing_tools/pubapis_jekyll.md",
    "_docs/publishing_tools/pubapis_oxygenxml.md",
    "_docs/publishing_tools/pubapis_switching_to_docs_as_code.md",
    "_docs/publishing_tools/publishingtools.md",
    "_docs/step_by_step_openapi_tutorial/openapi_tutorial.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_activity.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step1_openapi_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step2_info_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step3_servers_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step4_paths_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step5_components_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step6_security_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step7_tags_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_step8_externaldocs_object.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_openapi_tutorial_overview.md",
    "_docs/step_by_step_openapi_tutorial/pubapis_yaml.md",
    "_docs/testing_api_docs/testingdocs.md",
    "_docs/testing_api_docs/testingdocs_activity.md",
    "_docs/testing_api_docs/testingdocs_overview.md",
    "_docs/testing_api_docs/testingdocs_test_environment.md",
    "_docs/testing_api_docs/testingdocs_test_your_instructions.md",
    "_docs/testing_api_docs/testingdocs_testing_assumptions.md",
    "_docs/the_writing_process/docapis_information_gathering.md",
    "_docs/the_writing_process/docapis_planning.md",
    "_docs/the_writing_process/docapis_publishing.md",
    "_docs/the_writing_process/docapis_reviewing.md",
    "_docs/the_writing_process/docapis_writing.md",
    "_docs/the_writing_process/docapis_writing_process_overview.md",
    "_docs/the_writing_process/writing_process.md",
    "_docs/thriving_in_the_api_doc_space/docapis_find_open_source_project.md",
    "_docs/thriving_in_the_api_doc_space/docapis_work_on_conceptual_topic.md",
    "_docs/thriving_in_the_api_doc_space/jobapis.md",
    "_docs/thriving_in_the_api_doc_space/jobapis_learning_code.md",
    "_docs/thriving_in_the_api_doc_space/jobapis_location.md",
    "_docs/thriving_in_the_api_doc_space/jobapis_overview.md",
    "_docs/using_an_api_like_a_developer/docapis_access_json_values.md",
    "_docs/using_an_api_like_a_developer/docapis_analyze_json.md",
    "_docs/using_an_api_like_a_developer/docapis_curl_with_petstore.md",
    "_docs/using_an_api_like_a_developer/docapis_diving_into_dot_notation.md",
    "_docs/using_an_api_like_a_developer/docapis_get_auth_keys.md",
    "_docs/using_an_api_like_a_developer/docapis_install_curl.md",
    "_docs/using_an_api_like_a_developer/docapis_json_console.md",
    "_docs/using_an_api_like_a_developer/docapis_make_curl_call.md",
    "_docs/using_an_api_like_a_developer/docapis_postman.md",
    "_docs/using_an_api_like_a_developer/docapis_scenario_for_using_weather_api.md",
    "_docs/using_an_api_like_a_developer/docapis_understand_curl.md",
    "_docs/using_an_api_like_a_developer/likeadeveloper.md"
]

# Convert the flat list of repo files into a set for efficient lookup
existing_files_set = set(repo_files_structure)

valid_links = []
broken_links = []

for link_html in internal_links_to_validate:
    link_md = link_html.replace(".html", ".md")
    found = False
    for subdir in known_subdirectories:
        potential_path = f"_docs/{subdir}/{link_md}"
        if potential_path in existing_files_set:
            valid_links.append({"link": link_html, "path": potential_path})
            found = True
            break  # Found in one subdir, no need to check others
    if not found:
        # As a fallback, check if the file exists directly under _docs (e.g. for index.md)
        # This case is not explicitly in the prompt but good for robustness.
        # However, the prompt implies all files are within the known_subdirectories.
        # For now, sticking to the prompt's logic. If workshop.md is in _docs/course_overview/workshop.md
        # it will be found. If it were _docs/workshop.md, it would be missed by current logic.
        # The current known_subdirectories and ls output should cover this.
        broken_links.append(link_html)

print("Valid links:")
print(json.dumps(valid_links, indent=4))
print("\nBroken links:")
print(json.dumps(broken_links, indent=4))
